version: '3.9'

services:
  postgres:
    image: 'postgres:latest'
    container_name: 'kitchen-postgres'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=kitchen'

  postgres1:
    image: 'postgres:latest'
    container_name: 'waiter-postgres'
    ports:
      - 5433:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=1234'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=waiter'