spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kitchen
    username: postgres
    password: 1234

  liquibase:
    change-log: classpath:/db/db.changelog.xml

mybatis:
  mapper-locations: classpath:mybatis/mappers/*.xml
  type-aliases-package: ru.liga.restaurant.kitchen.model.entity
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: ru.liga.restaurant.kitchen.custom

service:
  host:
    waiter: localhost:8070/order