spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kitchen
    username: postgres
    password: 1234

  liquibase:
    change-log: classpath:/db/db.changelog.xml