server:
  port: 8070

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/waiter
    username: postgres
    password: 1234

  liquibase:
    change-log: classpath:/db/db.changelog.xml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      number-topic: orderToKitchenTopic

springdoc:
  swagger-ui:
    path: /swagger-ui.html

service:
  host:
    kitchen: localhost:8080/kitchen