server:
  port: 8070

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/waiter
    username: postgres
    password: 1234

  liquibase:
    change-log: classpath:/db/db.changelog.xml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

service:
  host:
    kitchen: localhost:8080/kitchen
